<div id="footer">
  Wiki source: <code>darcs get --lazy http://darcs.net/darcs-wiki</code>
  <br/>
  Powered by <a href="http://gitit.net/">darcsit (aka gitit)</a>
  <br/>
  <a href="http://flattr.com/thing/943161/Darcs-free-and-open-source-cross-platform-version-control-system" target="_blank">
  <img src="http://api.flattr.com/button/flattr-badge-large.png" alt="Flattr this" title="Flattr this" border="0" /></a>
</div>
