<div id="header" style="vertical-align:top;">
  <a href="$base$/" title="Go to top page"><img src="$base$/img/logos/logo.png" style="vertical-align:top;" /></a>
  <div style="float:right;">
    $userbox()$
  </div>
  <div style="float:right; padding-top:.5em;">
    <form action="$base$/_search" method="post" id="searchform">
     <input type="text" name="patterns" id="patterns"/>
     <input type="submit" name="search" id="search" value="Search"/>
    </form>
  </div>
  <div style="float:right; padding-top:1em;">
    <a href="$base$/_index">all pages</a>&nbsp;&nbsp;
    <!-- <a href="$base$/_categories">categories</a>&nbsp;&nbsp; -->
    <a href="$base$/_activity">recent changes</a>&nbsp;&nbsp;
    </ul>
  </div>
</div>
